import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Outfit, Rubik } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import MainNav from "./components/navigation/main_nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfito",
  subsets: ["latin"],
});
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const materialSymbols = localFont({
  src: "./fonts/MaterialSymbolsRounded.woff2",
  weight: "100 900",
  variable: "--font-material-symbols",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"], // optional
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Futurama Is Dope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} ${outfit.variable} ${poppins.variable} ${materialSymbols.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MainNav />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
